name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: pwsh
        run: ./build.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: B70Pcie-win64-${{ github.sha }}
          path: build/bin/B70Pcie.exe
          if-no-files-found: error
